# Generated by Django 4.2.16 on 2026-09-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('state', models.CharField(default='Jharkhand', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='universities', to='master_data.district')),
                ('expertise_areas', models.ManyToManyField(blank=True, related_name='universities', to='master_data.expertisearea')),
                ('spoc', models.OneToOneField(blank=True, limit_choices_to={'role': 'hei_spoc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_spoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.JSONField(default=list, help_text='List of student name strings')),
                ('project_description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('FORMED', 'Team Formation'), ('PROPOSAL', 'Proposal'), ('DEVELOPMENT', 'Development'), ('PILOT', 'Pilot'), ('IMPLEMENTATION', 'Implementation'), ('IMPACT', 'Impact')], default='FORMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='challenges.challenge')),
                ('faculty_mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty_mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_teams', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='universities.university')),
            ],
        ),
    ]
