# Generated by Django 4.2.16 on 2026-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='project_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
