# Generated by Django 4.2.16 on 2026-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_projectteam_domain_projectteam_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='departments',
            field=models.TextField(blank=True, help_text='Comma separated list of departments/disciplines'),
        ),
        migrations.AddField(
            model_name='university',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='facilities',
            field=models.TextField(blank=True, help_text='Innovation/incubation facilities'),
        ),
        migrations.AddField(
            model_name='university',
            name='institution_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='registration_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='hei_verifications/'),
        ),
    ]
