# Generated by Django 4.2.16 on 2026-09-08 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_milestone_description_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaries_count', models.IntegerField(default=0, help_text='Number of people directly benefiting')),
                ('cost_incurred', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost in INR', max_digits=12)),
                ('adoption_rate', models.CharField(blank=True, help_text='E.g., 85% of target population', max_length=100)),
                ('before_metrics', models.TextField(blank=True, help_text='State of the problem before intervention')),
                ('after_metrics', models.TextField(blank=True, help_text='State of the problem after intervention')),
                ('outcome_evidence', models.FileField(blank=True, null=True, upload_to='impact_evidence/%Y/%m/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('project_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_record', to='universities.projectteam')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
