# Generated by Django 4.2.16 on 2026-09-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='normalization_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='challenge',
            name='normalized_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='original_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
