# Generated by Django 4.2.16 on 2026-09-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('challenges', '0003_challenge_normalization_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='affected_population',
            field=models.PositiveSmallIntegerField(default=0, help_text='Scale of affected population (1–5; 0 = inferred from text)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ai_category_name',
            field=models.CharField(blank=True, help_text='AI-predicted category name — preserved even after admin override', max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ai_classification_reason',
            field=models.TextField(blank=True, help_text='AI-generated classification explanation'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ai_confidence',
            field=models.FloatField(default=0.0, help_text='Raw AI confidence 0.0–1.0'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, help_text='When AI pipeline last ran', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='classification_source',
            field=models.CharField(blank=True, choices=[('ai', 'AI (Gemini)'), ('keyword', 'Keyword Rules'), ('fallback', 'Fallback')], default='', help_text='Source of current category: ai, keyword, or fallback', max_length=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=0, help_text='Recurrence frequency (1–5; 0 = not yet assessed)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='manual_category',
            field=models.ForeignKey(blank=True, help_text='Admin-chosen category override (null = accepted AI result)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_challenges', to='master_data.category'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='manual_priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Admin-chosen priority override (blank = accepted AI result)', max_length=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='priority_breakdown',
            field=models.JSONField(default=dict, help_text='Factor-by-factor priority breakdown'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='priority_reason',
            field=models.TextField(blank=True, help_text='Human-readable explanation of priority score'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='Calculated priority score 0–100'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='severity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Severity of impact (1–5; 0 = not yet assessed)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='urgency',
            field=models.PositiveSmallIntegerField(default=0, help_text='Urgency of intervention (1–5; 0 = inferred from text)'),
        ),
    ]
