# Generated by Django 4.2.16 on 2026-09-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0004_ai_classification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ai_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When admin accepted the AI classification', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ai_accepted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who explicitly accepted the AI classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ai_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
