# Generated by Django 4.2.16 on 2026-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_ai_acceptance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ai_visual_evidence',
            field=models.TextField(blank=True, help_text='AI-extracted visual evidence from attached photos'),
        ),
    ]
