# Generated by Django 4.2.16 on 2026-09-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0006_challenge_ai_visual_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Sentence-transformer embedding vector (list of floats)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DuplicateFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Cosine similarity between the two challenge embeddings (0.0–1.0)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("confirmed_duplicate", "Confirmed Duplicate"),
                            ("not_duplicate", "Not a Duplicate"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge_a",
                    models.ForeignKey(
                        help_text="First challenge in the potential duplicate pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_flags_as_a",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "challenge_b",
                    models.ForeignKey(
                        help_text="Second challenge in the potential duplicate pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_flags_as_b",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("challenge_a", "challenge_b")},
            },
        ),
    ]
