# Generated by Django 4.2.16 on 2026-09-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('challenges', '0007_challenge_embedding_duplicateflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='twin_association_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Status of the AI-suggested problem twin association.', max_length=20),
        ),
        migrations.CreateModel(
            name='ProblemTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(help_text='AI-generated common problem title', max_length=300)),
                ('status', models.CharField(choices=[('NEW', 'New Candidate'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('ESCALATED', 'Escalated')], default='MEDIUM', max_length=20)),
                ('ai_confidence', models.FloatField(default=0.0, help_text='0.0 to 1.0 confidence score')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Generated reasoning explaining why these challenges form this Twin')),
                ('first_reported', models.DateTimeField(blank=True, null=True)),
                ('last_reported', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='problem_twins', to='master_data.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='problem_twins', to='master_data.district')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='problem_twin',
            field=models.ForeignKey(blank=True, help_text='The underlying real-world civic problem this report belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_challenges', to='challenges.problemtwin'),
        ),
    ]
