# Generated by Django 4.2.16 on 2026-09-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_confidence_threshold', models.FloatField(default=0.7)),
                ('duplicate_similarity_threshold', models.FloatField(default=0.85)),
                ('weight_severity', models.FloatField(default=0.3)),
                ('weight_frequency', models.FloatField(default=0.2)),
                ('weight_validation', models.FloatField(default=0.2)),
                ('weight_population', models.FloatField(default=0.15)),
                ('weight_urgency', models.FloatField(default=0.15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
            },
        ),
    ]
