# Generated by Django 4.2.16 on 2026-09-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'industry_partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='industry_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('MENTORSHIP', 'Mentorship'), ('FUNDING', 'Funding'), ('PILOT', 'Pilot Support'), ('INFRASTRUCTURE', 'Infrastructure'), ('OTHER', 'Other')], max_length=20)),
                ('contribution_details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='industry.industrypartner')),
                ('project_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='universities.projectteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
