# Generated by Django 4.2.16 on 2026-09-10 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("universities", "0003_university_address_university_departments_and_more"),
        ("industry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryMentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mentor_name", models.CharField(max_length=200)),
                (
                    "mentor_contact",
                    models.CharField(help_text="Email or phone", max_length=200),
                ),
                ("expertise_area", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="industrypartner",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("STARTUP", "Startup"),
                    ("MSME", "MSME"),
                    ("COMPANY", "Company"),
                    ("OTHER", "Other"),
                ],
                default="COMPANY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="industrypartner",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="MSME/Startup/Company registration number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="industrypartner",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="industrypartner",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="industrypartner",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="industrypartner",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_industry_partners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnership",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount in INR",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partnership",
            name="funding_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="partnership",
            name="funding_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMITTED", "Committed"),
                    ("DISBURSED", "Disbursed"),
                    ("UTILIZED", "Utilized"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partnership",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_partnerships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnership",
            name="response_note",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="project_documents/%Y/%m/")),
                ("description", models.CharField(blank=True, max_length=300)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_documents",
                        to="universities.projectteam",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_project_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="industry.industrymentor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="industrymentor",
            name="industry_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_mentors",
                to="industry.industrypartner",
            ),
        ),
        migrations.AddField(
            model_name="industrymentor",
            name="project_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industry_mentors",
                to="universities.projectteam",
            ),
        ),
    ]
